pipeline {
    agent any
    stages {
        stage('Installing dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage("Build") {
            steps {
                sh 'npm build'
            }
        }
    }
}